### ISSUE TITLE
idea使用插件出现的问题

### ISSUE THREAD

**Issue by timgodtim** [SweetInk/jrebel-mybatisplus#8]
集成插件后，修改了xml 报的以下错误 大神看一下，我该如何解决
2019-11-19 13:33:30 JRebel: Reloading SQL maps
2019-11-19 13:33:30,306 [DefaultQuartzScheduler_Worker-1] ERROR (org.quartz.core.JobRunShell.java:211) - Job XIR_SYSJOB_GROUP_NAME.tradeMatchServiceJob threw an unhandled Exception: 
java.lang.RuntimeException: Failed to parse mapping resource: 'file:/D:/-app/target/classes/sqlMapper/Instrument/BondMapper.xml'
	at org.zeroturnaround.jrebel.mybatis.SqlMapReloader.reconfigureMapping(SqlMapReloader.java:209) ~[SqlMapReloader.class:?]
	at org.zeroturnaround.jrebel.mybatis.SqlMapReloader.reconfigureAdditionalMappings(SqlMapReloader.java:188) ~[SqlMapReloader.class:?]
	at org.zeroturnaround.jrebel.mybatis.SqlMapReloader.reconfigure(SqlMapReloader.java:169) ~[SqlMapReloader.class:?]
	at org.zeroturnaround.jrebel.mybatis.SqlMapReloader.reload(SqlMapReloader.java:113) ~[SqlMapReloader.class:?]
	at org.apache.ibatis.session.defaults.DefaultSqlSessionFactory.openSessionFromDataSource(DefaultSqlSessionFactory.java:40004) ~[mybatis-3.5.1.jar:3.5.1]
	at org.apache.ibatis.session.defaults.DefaultSqlSessionFactory.openSession(DefaultSqlSessionFactory.java:57) ~[mybatis-3.5.1.jar:3.5.1]
	at org.mybatis.spring.SqlSessionUtils.getSqlSession(SqlSessionUtils.java:98) ~[mybatis-spring-2.0.1.jar:2.0.1]
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:428) ~[mybatis-spring-2.0.1.jar:2.0.1]
	at com.sun.proxy.$Proxy55.selectOne(Unknown Source) ~[?:?]
	at org.mybatis.spring.SqlSessionTemplate.selectOne(SqlSessionTemplate.java:166) ~[mybatis-spring-2.0.1.jar:2.0.1]
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:87) ~[mybatis-3.5.1.jar:3.5.1]
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:58) ~[mybatis-3.5.1.jar:3.5.1]
	at com.sun.proxy.$Proxy88.getSysParam(Unknown Source) ~[?:?]
	at com..platform.app.sysManage.service.impl.SysParamServiceImpl.getSysParam(SysParamServiceImpl.java:43) ~[-platform-app-2.0.0.0.jar:?]
	at sun.reflect.GeneratedMethodAccessor3246.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:45005) ~[?:1.8.0_92]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_92]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343) ~[spring-aop-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198) ~[spring-aop-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:295) ~[spring-tx-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98) ~[spring-tx-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93) ~[spring-aop-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) ~[spring-aop-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at com.sun.proxy.$Proxy192.getSysParam(Unknown Source) ~[?:?]
	at com..platform.app.tradeMatch.service.impl.TradeMatchServiceImpl.getEnableCfetsMatch(TradeMatchServiceImpl.java:171) ~[-platform-app-2.0.0.0.jar:?]
	at com..platform.app.tradeMatch.service.impl.TradeMatchServiceImpl.beginMatch(TradeMatchServiceImpl.java:206) ~[-platform-app-2.0.0.0.jar:?]
	at com..platform.app.tradeMatch.service.impl.TradeMatchServiceJob.Process(TradeMatchServiceJob.java:12) ~[-platform-app-2.0.0.0.jar:?]
	at com..platform.app.schedule.entity.ScheduleJob.execute(ScheduleJob.java:42) ~[-platform-app-common-2.0.0.0.jar:?]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202) [quartz-2.2.1.jar:?]
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) [quartz-2.2.1.jar:?]
Caused by: org.apache.ibatis.builder.BuilderException: Error creating document instance.  Cause: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at org.apache.ibatis.parsing.XPathParser.createDocument(XPathParser.java:260) ~[mybatis-3.5.1.jar:3.5.1]
	at org.apache.ibatis.parsing.XPathParser.<init>(XPathParser.java:121) ~[mybatis-3.5.1.jar:3.5.1]
	at org.apache.ibatis.builder.xml.XMLMapperBuilder.<init>(XMLMapperBuilder.java:70) ~[mybatis-3.5.1.jar:3.5.1]
	at org.zeroturnaround.jrebel.mybatis.SqlMapReloader.reconfigureMapping(SqlMapReloader.java:200) ~[SqlMapReloader.class:?]
	... 32 more
Caused by: org.xml.sax.SAXParseException: Content is not allowed in prolog.
	at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source) ~[org.apache.xerces-2.9.0.jar:?]
	at org.apache.xerces.util.ErrorHandlerWrapper.fatalError(Unknown Source) ~[org.apache.xerces-2.9.0.jar:?]
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source) ~[org.apache.xerces-2.9.0.jar:?]
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source) ~[org.apache.xerces-2.9.0.jar:?]
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source) ~[org.apache.xerces-2.9.0.jar:?]
	at org.apache.xerces.impl.XMLScanner.reportFatalError(Unknown Source) ~[org.apache.xerces-2.9.0.jar:?]
	at org.apache.xerces.impl.XMLDocumentScannerImpl$PrologDispatcher.dispatch(Unknown Source) ~[org.apache.xerces-2.9.0.jar:?]
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source) ~[org.apache.xerces-2.9.0.jar:?]
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) ~[org.apache.xerces-2.9.0.jar:?]
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) ~[org.apache.xerces-2.9.0.jar:?]
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source) ~[org.apache.xerces-2.9.0.jar:?]
	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source) ~[org.apache.xerces-2.9.0.jar:?]
	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source) ~[org.apache.xerces-2.9.0.jar:?]
	at org.apache.ibatis.parsing.XPathParser.createDocument(XPathParser.java:258) ~[mybatis-3.5.1.jar:3.5.1]
	at org.apache.ibatis.parsing.XPathParser.<init>(XPathParser.java:121) ~[mybatis-3.5.1.jar:3.5.1]
	at org.apache.ibatis.builder.xml.XMLMapperBuilder.<init>(XMLMapperBuilder.java:70) ~[mybatis-3.5.1.jar:3.5.1]
	at org.zeroturnaround.jrebel.mybatis.SqlMapReloader.reconfigureMapping(SqlMapReloader.java:200) ~[SqlMapReloader.class:?]
	... 32 more
2019-11-19 13:33:30,321 [DefaultQuartzScheduler_Worker-1] ERROR (org.quartz.core.ErrorLogger.java:2425) - Job (XIR_SYSJOB_GROUP_NAME.tradeMatchServiceJob threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception.
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213) [quartz-2.2.1.jar:?]
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) [quartz-2.2.1.jar:?]
Caused by: java.lang.RuntimeException: Failed to parse mapping resource: 'file:/D:/xRisk5.1/-platform-app/target/classes/sqlMapper/Instrument/BondMapper.xml'
	at org.zeroturnaround.jrebel.mybatis.SqlMapReloader.reconfigureMapping(SqlMapReloader.java:209) ~[SqlMapReloader.class:?]
	at org.zeroturnaround.jrebel.mybatis.SqlMapReloader.reconfigureAdditionalMappings(SqlMapReloader.java:188) ~[SqlMapReloader.class:?]
	at org.zeroturnaround.jrebel.mybatis.SqlMapReloader.reconfigure(SqlMapReloader.java:169) ~[SqlMapReloader.class:?]
	at org.zeroturnaround.jrebel.mybatis.SqlMapReloader.reload(SqlMapReloader.java:113) ~[SqlMapReloader.class:?]
	at org.apache.ibatis.session.defaults.DefaultSqlSessionFactory.openSessionFromDataSource(DefaultSqlSessionFactory.java:40004) ~[mybatis-3.5.1.jar:3.5.1]
	at org.apache.ibatis.session.defaults.DefaultSqlSessionFactory.openSession(DefaultSqlSessionFactory.java:57) ~[mybatis-3.5.1.jar:3.5.1]
	at org.mybatis.spring.SqlSessionUtils.getSqlSession(SqlSessionUtils.java:98) ~[mybatis-spring-2.0.1.jar:2.0.1]
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:428) ~[mybatis-spring-2.0.1.jar:2.0.1]
	at com.sun.proxy.$Proxy55.selectOne(Unknown Source) ~[?:?]
	at org.mybatis.spring.SqlSessionTemplate.selectOne(SqlSessionTemplate.java:166) ~[mybatis-spring-2.0.1.jar:2.0.1]
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:87) ~[mybatis-3.5.1.jar:3.5.1]
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:58) ~[mybatis-3.5.1.jar:3.5.1]
	at com.sun.proxy.$Proxy88.getSysParam(Unknown Source) ~[?:?]
	at com..platform.app.sysManage.service.impl.SysParamServiceImpl.getSysParam(SysParamServiceImpl.java:43) ~[-platform-app-2.0.0.0.jar:?]
	at sun.reflect.GeneratedMethodAccessor3246.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:45005) ~[?:1.8.0_92]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_92]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343) ~[spring-aop-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198) ~[spring-aop-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:295) ~[spring-tx-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98) ~[spring-tx-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93) ~[spring-aop-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) ~[spring-aop-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at com.sun.proxy.$Proxy192.getSysParam(Unknown Source) ~[?:?]
	at com..platform.app.tradeMatch.service.impl.TradeMatchServiceImpl.getEnableCfetsMatch(TradeMatchServiceImpl.java:171) ~[-platform-app-2.0.0.0.jar:?]
	at com..platform.app.tradeMatch.service.impl.TradeMatchServiceImpl.beginMatch(TradeMatchServiceImpl.java:206) ~[-platform-app-2.0.0.0.jar:?]
	at com..platform.app.tradeMatch.service.impl.TradeMatchServiceJob.Process(TradeMatchServiceJob.java:12) ~[-platform-app-2.0.0.0.jar:?]
	at com..platform.app.schedule.entity.ScheduleJob.execute(ScheduleJob.java:42) ~[-platform-app-common-2.0.0.0.jar:?]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202) ~[quartz-2.2.1.jar:?]
	... 1 more
Caused by: org.apache.ibatis.builder.BuilderException: Error creating document instance.  Cause: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at org.apache.ibatis.parsing.XPathParser.createDocument(XPathParser.java:260) ~[mybatis-3.5.1.jar:3.5.1]
	at org.apache.ibatis.parsing.XPathParser.<init>(XPathParser.java:121) ~[mybatis-3.5.1.jar:3.5.1]
	at org.apache.ibatis.builder.xml.XMLMapperBuilder.<init>(XMLMapperBuilder.java:70) ~[mybatis-3.5.1.jar:3.5.1]
	at org.zeroturnaround.jrebel.mybatis.SqlMapReloader.reconfigureMapping(SqlMapReloader.java:200) ~[SqlMapReloader.class:?]
	at org.zeroturnaround.jrebel.mybatis.SqlMapReloader.reconfigureAdditionalMappings(SqlMapReloader.java:188) ~[SqlMapReloader.class:?]
	at org.zeroturnaround.jrebel.mybatis.SqlMapReloader.reconfigure(SqlMapReloader.java:169) ~[SqlMapReloader.class:?]
	at org.zeroturnaround.jrebel.mybatis.SqlMapReloader.reload(SqlMapReloader.java:113) ~[SqlMapReloader.class:?]
	at org.apache.ibatis.session.defaults.DefaultSqlSessionFactory.openSessionFromDataSource(DefaultSqlSessionFactory.java:40004) ~[mybatis-3.5.1.jar:3.5.1]
	at org.apache.ibatis.session.defaults.DefaultSqlSessionFactory.openSession(DefaultSqlSessionFactory.java:57) ~[mybatis-3.5.1.jar:3.5.1]
	at org.mybatis.spring.SqlSessionUtils.getSqlSession(SqlSessionUtils.java:98) ~[mybatis-spring-2.0.1.jar:2.0.1]
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:428) ~[mybatis-spring-2.0.1.jar:2.0.1]
	at com.sun.proxy.$Proxy55.selectOne(Unknown Source) ~[?:?]
	at org.mybatis.spring.SqlSessionTemplate.selectOne(SqlSessionTemplate.java:166) ~[mybatis-spring-2.0.1.jar:2.0.1]
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:87) ~[mybatis-3.5.1.jar:3.5.1]
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:58) ~[mybatis-3.5.1.jar:3.5.1]
	at com.sun.proxy.$Proxy88.getSysParam(Unknown Source) ~[?:?]
	at com..platform.app.sysManage.service.impl.SysParamServiceImpl.getSysParam(SysParamServiceImpl.java:43) ~[-platform-app-2.0.0.0.jar:?]
	at sun.reflect.GeneratedMethodAccessor3246.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:45005) ~[?:1.8.0_92]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_92]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343) ~[spring-aop-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198) ~[spring-aop-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:295) ~[spring-tx-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98) ~[spring-tx-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93) ~[spring-aop-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) ~[spring-aop-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at com.sun.proxy.$Proxy192.getSysParam(Unknown Source) ~[?:?]
	at com..platform.app.tradeMatch.service.impl.TradeMatchServiceImpl.getEnableCfetsMatch(TradeMatchServiceImpl.java:171) ~[-platform-app-2.0.0.0.jar:?]
	at com..platform.app.tradeMatch.service.impl.TradeMatchServiceImpl.beginMatch(TradeMatchServiceImpl.java:206) ~[-platform-app-2.0.0.0.jar:?]
	at com..platform.app.tradeMatch.service.impl.TradeMatchServiceJob.Process(TradeMatchServiceJob.java:12) ~[-platform-app-2.0.0.0.jar:?]
	at com..platform.app.schedule.entity.ScheduleJob.execute(ScheduleJob.java:42) ~[-platform-app-common-2.0.0.0.jar:?]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202) ~[quartz-2.2.1.jar:?]
	... 1 more
Caused by: org.xml.sax.SAXParseException: Content is not allowed in prolog.
	at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source) ~[org.apache.xerces-2.9.0.jar:?]
	at org.apache.xerces.util.ErrorHandlerWrapper.fatalError(Unknown Source) ~[org.apache.xerces-2.9.0.jar:?]
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source) ~[org.apache.xerces-2.9.0.jar:?]
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source) ~[org.apache.xerces-2.9.0.jar:?]
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source) ~[org.apache.xerces-2.9.0.jar:?]
	at org.apache.xerces.impl.XMLScanner.reportFatalError(Unknown Source) ~[org.apache.xerces-2.9.0.jar:?]
	at org.apache.xerces.impl.XMLDocumentScannerImpl$PrologDispatcher.dispatch(Unknown Source) ~[org.apache.xerces-2.9.0.jar:?]
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source) ~[org.apache.xerces-2.9.0.jar:?]
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) ~[org.apache.xerces-2.9.0.jar:?]
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) ~[org.apache.xerces-2.9.0.jar:?]
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source) ~[org.apache.xerces-2.9.0.jar:?]
	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source) ~[org.apache.xerces-2.9.0.jar:?]
	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source) ~[org.apache.xerces-2.9.0.jar:?]
	at org.apache.ibatis.parsing.XPathParser.createDocument(XPathParser.java:258) ~[mybatis-3.5.1.jar:3.5.1]
	at org.apache.ibatis.parsing.XPathParser.<init>(XPathParser.java:121) ~[mybatis-3.5.1.jar:3.5.1]
	at org.apache.ibatis.builder.xml.XMLMapperBuilder.<init>(XMLMapperBuilder.java:70) ~[mybatis-3.5.1.jar:3.5.1]
	at org.zeroturnaround.jrebel.mybatis.SqlMapReloader.reconfigureMapping(SqlMapReloader.java:200) ~[SqlMapReloader.class:?]
	at org.zeroturnaround.jrebel.mybatis.SqlMapReloader.reconfigureAdditionalMappings(SqlMapReloader.java:188) ~[SqlMapReloader.class:?]
	at org.zeroturnaround.jrebel.mybatis.SqlMapReloader.reconfigure(SqlMapReloader.java:169) ~[SqlMapReloader.class:?]
	at org.zeroturnaround.jrebel.mybatis.SqlMapReloader.reload(SqlMapReloader.java:113) ~[SqlMapReloader.class:?]
	at org.apache.ibatis.session.defaults.DefaultSqlSessionFactory.openSessionFromDataSource(DefaultSqlSessionFactory.java:40004) ~[mybatis-3.5.1.jar:3.5.1]
	at org.apache.ibatis.session.defaults.DefaultSqlSessionFactory.openSession(DefaultSqlSessionFactory.java:57) ~[mybatis-3.5.1.jar:3.5.1]
	at org.mybatis.spring.SqlSessionUtils.getSqlSession(SqlSessionUtils.java:98) ~[mybatis-spring-2.0.1.jar:2.0.1]
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:428) ~[mybatis-spring-2.0.1.jar:2.0.1]
	at com.sun.proxy.$Proxy55.selectOne(Unknown Source) ~[?:?]
	at org.mybatis.spring.SqlSessionTemplate.selectOne(SqlSessionTemplate.java:166) ~[mybatis-spring-2.0.1.jar:2.0.1]
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:87) ~[mybatis-3.5.1.jar:3.5.1]
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:58) ~[mybatis-3.5.1.jar:3.5.1]
	at com.sun.proxy.$Proxy88.getSysParam(Unknown Source) ~[?:?]
	at com..platform.app.sysManage.service.impl.SysParamServiceImpl.getSysParam(SysParamServiceImpl.java:43) ~[-platform-app-2.0.0.0.jar:?]
	at sun.reflect.GeneratedMethodAccessor3246.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:45005) ~[?:1.8.0_92]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_92]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343) ~[spring-aop-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198) ~[spring-aop-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:295) ~[spring-tx-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98) ~[spring-tx-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93) ~[spring-aop-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) ~[spring-aop-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at com.sun.proxy.$Proxy192.getSysParam(Unknown Source) ~[?:?]
	at com..platform.app.tradeMatch.service.impl.TradeMatchServiceImpl.getEnableCfetsMatch(TradeMatchServiceImpl.java:171) ~[-platform-app-2.0.0.0.jar:?]
	at com..platform.app.tradeMatch.service.impl.TradeMatchServiceImpl.beginMatch(TradeMatchServiceImpl.java:206) ~[-platform-app-2.0.0.0.jar:?]
	at com..platform.app.tradeMatch.service.impl.TradeMatchServiceJob.Process(TradeMatchServiceJob.java:12) ~[-platform-app-2.0.0.0.jar:?]
	at com..platform.app.schedule.entity.ScheduleJob.execute(ScheduleJob.java:42) ~[-platform-app-common-2.0.0.0.jar:?]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202) ~[quartz-2.2.1.jar:?]
	... 1 more

**Comment by SweetInk** [comment]
检查下你的`BondMapper.xml`是否有语法错误，或者贴出来看下

**Comment by timgodtim** [comment]
感谢回答~ 
BondMapper.xml ，没有错误
现在情况是这样的  
我用的idea，项目启动后，我修改mapper.xml 项目中报错 就上面的那个错误，
我修改的mapper.xml在target\classes也修改成功，但是项目中的  依然用的是 修改之前的xml，实际之前的xml已经不存在了 。才报的那个错。
 
我想 是不是我idea tomcat中配置的原因 导致的现在的问题

**Comment by SweetInk** [comment]
看你的异常堆栈，你应该用的是`mybatis`,而不是`mybatis-plus`，建议你`clean`整个项目，再`rebuild`试试.或者整个项目重新导入.
